
# Sample:
# Rscript RunBPRF.R -xfpkm_for_cls.csv -y../resp_tsne_rseq.csv -b10000 -mwgcna_cluster_membership_method_A.csv -c1 -osyntBlk_tsne_cutin -rsyntBlk_tsne_cutin -nt32
#     -x: predictors
#     -y: responses
#     -b: permutation runs
#     -m: gene cluster membership file generated by wgcna
#     -c: the index of column in the response input file (specified by "-y"). Because block.pc.rf uses single-column values as the response, this option specifies the column to be used as the response variable
#     -nt: nThreads, number of cpus requested
#     -o: path to write the output (optional)
#     -r: path to write the model evaluation report (optional)
#     -l (optional): lasso penalty, ranging from 0 to 1
require(randomForest)
require(doParallel)

path=c("/work/LAS/myn-lab/KChen/BlockPC.RF/updateX.R",
       "/work/LAS/myn-lab/KChen/BlockPC.RF/sPCA.R",
       "/work/LAS/myn-lab/KChen/BlockPC.RF/blockpc.RF.R",
       "/work/LAS/myn-lab/KChen/BlockPC.RF/variable.importance.R")
for(pa in path) source(pa)

args = commandArgs(trailingOnly=T)
lab=c("-x","-y","-b","-m","-c","-o","-r","-nt", "-l")
idx=sapply(lab, function(ll)ifelse(sum(grepl(ll,args))==1,which(grepl(ll,args)),NA))
args1=rep("",length(lab));names(args1)=lab
for(i in 1:length(idx)){
	if(!is.na(idx[i])){
	args1[i]=gsub(names(idx)[i],"",args[idx[i]])} else args1[i]=NA
}
args=args1

x=read.csv(args["-x"],row.names=1)
y=read.csv(args["-y"],row.names=1)

pp=as.numeric(args["-b"])
pc=as.numeric(args["-c"])

y=y[,pc]

synt.cls=read.csv(args["-m"], row.names=1)
cls=as.numeric(synt.cls[,"Gene_Cluster"])
names(cls)=rownames(synt.cls)
if(sum(cls==0)==0) cls[cls==max(cls)]=0

if(!is.na(args["-l"])){
        l <- as.numeric(args["-l"])
} else l <- 0

	   
bprf=block.pc.rf(X=x, Y=y, lv=1, lamda=l, cluster=cls,quality.check=F, package="randomForest")

nt=as.numeric(args["-nt"])

cat("Calculate variable importance...","\n")
gene.rank=importance(bprf, idx.x=1:ncol(bprf$X.block),permutation=pp, nThreads=nt)
gene.rank=gene.rank[order(gene.rank[,"dR2"], gene.rank[,"dRMSE"], gene.rank[,"dAccuracy"], decreasing=T),]

r2=bprf$r2.forest
rmse=bprf$rmse.forest
accuracy=mean(bprf$accuracy)

if(!is.na(args["-o"])){
        outFile=paste0(args["-o"],".txt")
        write.table(gene.rank,outFile)
}
if(!is.na(args["-r"]))
{
        reportFile=paste0(args["-r"],".report")
        cat("BPRF:R2=",r2,"\n","RMSE=",rmse,"\n","Accuracy=",accuracy,"\n",file=reportFile)
}


cat("Job Finished", "\n")
